site_name: BEQCatalogue
site_url: 'https://beqcatalogue.readthedocs.io'
copyright: 'Copyright &copy; 2023 3ll3d00d / aron7awol / mobe1969 / halcyon888 / t1g8rsfan'
theme:
  name: 'material'
  logo: 'img/icon.png'
  favicon: 'img/icon.ico'
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - tablefilter/tablefilter.js
  - javascripts/tables.js
extra_css:
  - css/extra.css
  - tablefilter/style/tablefilter.css
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - tables
nav:
  - aron7awol: aron7awol.md
  - mobe1969: mobe1969.md
  - halcyon888: halcyon888.md
  - t1g8rsfan: t1g8rsfan.md
  - kaelaria: kaelaria.md
plugins:
  - search